### ISSUE TITLE
Url with parameters can't be added

### ISSUE THREAD

**Issue by frankrousseau** [Piour/cozy-feeds#13]
Hello there, I would like to follow this feed but it doesn't work. Is it possible to fix it :)? 

http://mindfulcyborgs.com/shows?format=RSS

By the way thank you for Cozy Feeds. I can follow easily my favortie blogs with it.

**Comment by Piour** [comment]
This issue is solved in the nextgen feed reader for cozy : https://github.com/pierrerousseau/zero-feeds
