### ISSUE TITLE
wrong characters

### ISSUE THREAD

**Issue by christi9n** [Piour/cozy-feeds#14]
Hi,
I use Iceweasel 37.1 and Midori 0.4.3 (Debia 7.8 - 64bits)
Accented characters are wrong ... and replaced by "?"
![capture du 2015-04-14 00 27 54](https://cloud.githubusercontent.com/assets/11626946/7126840/25a48cc6-e23d-11e4-9d23-dedb9ba0312e.png)
Many thanks for your application.
Christian

**Comment by christi9n** [comment]
Pierre,
J'écris en anglais pour partager avec les non frenchies ;o)

Following our discussion yesterday, you'll find herewith 2 feeds which gives wrong characters
http://feeds.feedburner.com/Cepid-AnnoncesEmploi?format=xml
http://www.ebd.fr/ewb_pages/f/fil_offres_emploi.php

Many thanks again for your applications ;o))

**Comment by Piour** [comment]
Hi, 
thanks for reporting this issue, can you tell me if it is working with this application : https://github.com/pierrerousseau/zero-feeds (it's the next version of cozy-feeds) for the first feed (for me it seems to be ok).
For the second url, I'll check it very soon.

**Comment by christi9n** [comment]
Hi Pierre,
First feed is OK with "zero-feeds" but second one is KO.
Following our discussion last week at Cozzy meet up, I'm now persuaded it comes from the feed itself wich is not well formatted!
I keep "zero-feed" in my cozy to do some other tests.
Speak to you soon,
Christian

**Comment by Piour** [comment]
They just don't send it in utf-8 and they don't give any hint on the encoding (or i don't know where to find this information). I worked a bit on it and found a "it works" workaround. Your second feed is now readable. Try to have a look on all your feed that use accents or any special characters and tell me if you notice any problem.

**Comment by christi9n** [comment]
Well done Pierre, now my second feed is OK ;o)
I'll go back to you any way if I see any others pb with encoding.
Ciao, see you.
Christian

**Comment by Piour** [comment]
Thx for testing :)
