### ISSUE TITLE
Can't import OPML files generated by feedly

### ISSUE THREAD

**Issue by zedalaye** [Piour/cozy-feeds#15]
I want to migrate my feeds from Feedly to Cozy Feeds so I exported my feeds from feedly top OPML. When I use the "import" button of Cozy Feeds and I select the OPML file I get the error : "This file can not be imported."

**Comment by Piour** [comment]
I tried on a very simple example on the new version of cozy-feeds https://github.com/pierrerousseau/zero-feeds, and it was working. 
Can you try on this version, and tell me if it is working. Probably not, but you may be lucky :)

**Comment by zedalaye** [comment]
@Piour I just can't install zero-feeds  on my cozy. Do it requires extra system dependencies ?

**Comment by Piour** [comment]
No, do you have any error message ?

**Comment by zedalaye** [comment]
I tried again, this time install worked, the app starts but looks horrible and import still don't work (see attached screenshot that shows both problems)

![zero_feeds](https://cloud.githubusercontent.com/assets/7906/7320359/64d83534-ea9c-11e4-9634-7b1d640d05c4.png)

**Comment by Piour** [comment]
Ok, the version on github should not be on github yet, and of course is broken ... I tell you as soon as I correct this.

**Comment by Piour** [comment]
Ok, it should work now, but it's better if you can confirm it. You need to install it again, and maybe reload the page.

**Comment by Piour** [comment]
I did create a feedly account, exported an opml file, and except that the feeds where not displayed in their categories at import (but all was ok after reloading) it worked. So it means that there is something that I don't handle correctly for one feed or one option. 

It means we have to find what. So or you can send me your opml file, otherwise I'll play more with feedly.

**Comment by zedalaye** [comment]
I installed the new version, the OPML file has been imported but it looks like it don't work : feeds can't be updated, and I still have that strange "spinner" at top left. (Note that I'm using Firefox 38 (beta))

After reload, all feeds have disappeared. I can send you my OPML file but how (your GitHub profile do not mention your email address) ?

![cozy_zero_feeds](https://cloud.githubusercontent.com/assets/7906/7332295/a8f17450-eb38-11e4-8f57-abd8f6ec230b.png)

**Comment by Piour** [comment]
We have to fix the spinner problem first. If it does not disappear it means that the application does not access to the database. Can you try to remove the app, install it again, go to the application and then hit ctrl-F5 and right click where you can except in the upper zero-feeds bar, and reload the frame ?

**Comment by Piour** [comment]
Ok, I found the problem. I messed up with the dependencies. On update, there was no problem, as old dependencies are not deleted. But on a new install, dependencies were not resolved, and the app was then not starting correctly.

If you update it again, everything should be back to normal.

**Comment by zedalaye** [comment]
The spinner problem has gone. But I still can't import my Feedly OPML file.

**Comment by ZeHiro** [comment]
Hello,

I had the same import problem. The problem seems to be that the MIME type is not set to text/x-opml+xml. Then whose responsability to set this: 
- Feedly?
- OS?

**Comment by Piour** [comment]
I'm not sure to understand how you solved this @ZeHiro : the problem is when you download the feedly opml on your disk ?

I think I can handle it on the app side, maybe an enconding problem or I dont know. I will try to export a feedly file under windows 7.

@zedalaye : what operating system are you using ?

**Comment by Piour** [comment]
ok, I exported a file under windows 7, and the import failed. This is the same import that worked for my previous test (linux os). 
So I have something to test it, you can hope for a solution :)

**Comment by ZeHiro** [comment]
The opml file was exported on w7 from feedly. When importing on the cozy, on w7, the 'type' attribute of the file was empty. So I searched for opml in the register, added a Content Type description (text/opml+xml or somerhing like that) in the w7 register. Next i retried the import on cozy without reboot or so, the file.type was right, and the opml file was imported.

**Comment by ZeHiro** [comment]
To complete my previous answer, but this needs to be confirmed, the MIME type is declared by the OS, and not the file as itself. As you checke th MIME type of the file to decide whether the import should be done or not, if the MIME type is not properly declared by the OS, then the check will fail, even if the opml file is correct.

**Comment by Piour** [comment]
Ah, I see, any idea what mime type is set by windows ?

**Comment by ZeHiro** [comment]
On my install, before changing it manually, no MIME type was declared by windows.
In the key : 
HKEY_USERS\S-1-5-21-3675852479-2980802970-892884109-356137_Classes\.opml

I added a "String Value" withe thie properties : 
Name :  Content Type
Type : REG_SZ
Data : text/x-ompl+xml

After that the MIME type was properly declared.
But I don't know if this fix is dirty or not, I know it works :)

**Comment by Piour** [comment]
I cant ask everybody to do that :p I think i will just accept files with the .opml extension, it should work. 

Thanks you very much for your help !

**Comment by zedalaye** [comment]
@Piour : From Ubuntu, IT WORKS ! Awesome ;-)

**Comment by Piour** [comment]
Great ! And from my side, I accept now all files with the .opml extension without checking mime type. So I could import a feedly opml files with windows.

Thanks a lot @zedalaye and @ZeHiro !
